# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.setEnabled(True)
        widget.resize(1000, 700)
        widget.setMinimumSize(QtCore.QSize(1000, 700))
        widget.setMaximumSize(QtCore.QSize(1000, 700))
        widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        widget.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(30, 60, 937, 573))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border-width: 5px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label.setLineWidth(6)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setProperty("setLineWidth", 5)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(widget)
        self.label_4.setGeometry(QtCore.QRect(59, 19, 71, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 19, 61, 20))
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(widget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 650, 60, 40))
        self.pushButton_2.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(198, 198, 198);")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(widget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 650, 60, 40))
        self.pushButton_3.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(198, 198, 198);")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setAutoExclusive(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(widget)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 650, 60, 40))
        self.pushButton_4.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(198, 198, 198);")
        self.pushButton_4.setText("")
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(widget)
        self.label_5.setGeometry(QtCore.QRect(461, 20, 24, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(widget)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(500, 20, 61, 20))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(262, 20, 48, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(widget)
        self.lineEdit.setGeometry(QtCore.QRect(320, 19, 61, 20))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(widget)
        self.comboBox.setGeometry(QtCore.QRect(770, 20, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_6 = QtWidgets.QLabel(widget)
        self.label_6.setGeometry(QtCore.QRect(650, 20, 91, 20))
        self.label_6.setObjectName("label_6")
        self.pushButton_6 = QtWidgets.QPushButton(widget)
        self.pushButton_6.setGeometry(QtCore.QRect(890, 20, 50, 21))
        self.pushButton_6.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(198, 198, 198);")
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setChecked(False)
        self.pushButton_6.setAutoExclusive(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "瀚维智能医疗"))
        self.label_4.setText(_translate("widget", "视频总帧数："))
        self.pushButton_2.setText(_translate("widget", "上一帧"))
        self.pushButton_3.setText(_translate("widget", "下一帧"))
        self.label_5.setText(_translate("widget", "FPS:"))
        self.label_2.setText(_translate("widget", "当前帧："))
        self.label_6.setText(_translate("widget", "病灶对应的帧数："))
        self.pushButton_6.setText(_translate("widget", "更新"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
